language: java
jdk:
  - openjdk11

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r irokocommerce *
  - mkdir -p deploy
  - mv irokocommerce.zip deploy/irokocommerce.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: backaws # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: jpnshop/irokocommerce #Github 주소

  - provider: codedeploy
      access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
      secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
      bucket: backaws # S3 버킷
      key: irokocommerce.zip # 빌드 파일을 압축해서 전달
      bundle_type: zip
      application: backaws # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
      deployment_group: backaws-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
      region: ap-northeast-2
      wait-until-deployed: true
      on:
        repo: jpnshop/irokocommerce

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - skaeo357@gmail.com